Add tag command
bankobotv14/BankoBot pull request #3
Opened 2021-01-21 18:12 UTC by NyCodeGHG

2021-01-25 12:28 UTC, NyCodeGHG commented
Tag Commands:

- [x] create-tag
- [x] create-alias
- [x] edit-tag
- [ ] info
- [x] delete-tag
- [ ] delete-alias
- [x] list
- [x] from
- [x] search
- [ ] raw
- [ ] transfer

2021-01-25 13:08 UTC, DRSchlaubi commented
for the raw command just post the tag to hastebin

2021-01-26 16:44 UTC, warriorzz commented on src/main/kotlin/de/nycode/bankobot/commands/tag/commands/TransferTagCommand.kt
> +                            "Der Tag \"${tag.name}\" wurde erfolgreich von ${message.author?.mention} zu ${member.mention} transferiert!"
Checks failed, :/

2021-01-26 17:45 UTC, DRSchlaubi approved these changes

2021-01-26 17:45 UTC, DRSchlaubi commented on src/main/kotlin/de/nycode/bankobot/commands/tag/commands/CreateAliasCommand.kt
> +        val tag = findTag(tagName) ?: return@invoke
you should make a tag argument. You can just use Argument.map and filter for it see docs and jdoodle command

2021-01-26 20:56 UTC, DRSchlaubi requested changes
I literally can't even click request changes

2021-01-27 12:28 UTC, NyCodeGHG commented
Please do not merge yet

2021-01-27 19:34 UTC, warriorzz approved these changes

2021-01-27 19:34 UTC, merged